### ISSUE TITLE
Jailbroken Apple TV?

### ISSUE THREAD

**Issue by PencilNotPen** [dmunozv04/iSponsorBlockTV#11]
Hi,

Do you think it would be possible to run this directly on the Apple TV if it were jailbroken?

Given that a jailbroken ATV can be attached to via SSH, and the filesystem is open to modification, could iSponsorBlockTV be installed and run directly on the device, without the need for another device?

If so, what changes would need to be made, and what requirements would be needed of the ATV in terms of available commands installed for it to work?

Thanks for a great tool!

**Comment by dmunozv04** [comment]
I don’t have a jailbroken Apple TV but it may be a better experience to port [iSponsorBlock the tweak](https://github.com/Galactic-Dev/iSponsorBlock) to apple TV by @Galactic-Dev. 
I don’t know if it’s possible to run python and pip on a jailbroken AppleTV and if airplay api is accessible from localhost. 
If you learn more about this, please let me know

**Comment by Galactic-Dev** [comment]
If my Apple TV didn't get updated I should be able to jailbreak it still. I could mess around with this and let you know what I find.

**Comment by dmunozv04** [comment]
> If my Apple TV didn't get updated I should be able to jailbreak it still. I could mess around with this and let you know what I find.

Thank you, that would be amazing

**Comment by PencilNotPen** [comment]
> I don’t have a jailbroken Apple TV but it may be a better experience to port [iSponsorBlock the tweak](https://github.com/Galactic-Dev/iSponsorBlock) to apple TV by @Galactic-Dev.
> I don’t know if it’s possible to run python and pip on a jailbroken AppleTV and if airplay api is accessible from localhost.
> If you learn more about this, please let me know

Yea, I thought the same thing and contacted the dev on iSponsorblock’s GitHub.

**Comment by oxixes** [comment]
With V2, this should be possible as long as a jailbroken Apple TV can run an arbitrary python program, therefore this should be closed.
