### ISSUE TITLE
bug or ?

### ISSUE THREAD

**Issue by arashtotti88** [dmunozv04/iSponsorBlockTV#114]
Hi there

I have a problem! I don't know if it is supposed to be like this or script doesn't work properly for me.

I managed to install and run the script and paired my LG TV and Apple TV.

I checked the sponsor's section in the video and it works perfectly  

https://www.youtube.com/watch?v=XWfKydsof10&t=292s

3:36 has a sponsor section and it skipped in my 2 devices perfectly.

my problem is I still getting YouTube ads like this :

![photo_2023-12-11_07-08-43](https://github.com/dmunozv04/iSponsorBlockTV/assets/45925072/638a6e38-f553-480a-8585-9dee7ef57640)

and I don't know this is supposed to be like this or it should be skipped.

I installed the script on Raspberry Pi 4 with the docker option without the graphical option
my config :

{
    "devices": [
        {
            "screen_id": "******************************",
            "name": "YouTube on TV"
        }
    ],
    "apikey": "",
    "skip_categories": [
        "sponsor",
        "selfpromo",
        "exclusive_access",
        "interaction",
        "poi_highlight",
        "intro",
        "outro",
        "preview",
        "filler",
        "music_offtopic"
    ],
    "channel_whitelist": [],
    "skip_count_tracking": true,
    "mute_ads": false,
    "skip_ads": false
}

thanks for your hard work

**Comment by oxixes** [comment]
The app will try to skip any ads possible. Unfortunately, it can’t skip ads that YouTube doesn’t allow you to skip, so this is not a problem, but rather a limitation that can’t be solved since YouTube doesn’t allow it.

**Comment by arashtotti88** [comment]
thanks a lot for rocket answer
