### ISSUE TITLE
Sponsor segment not skipped after manually seeking

### ISSUE THREAD

**Issue by Ivan0xFF** [dmunozv04/iSponsorBlockTV#12]
As the title says, the sponsor segment is not currently being skipped if you fast-forward or rewind a video.

Steps to reproduce:
1. Play a video on YouTube
2. Skip forward or rewind the video.
3. Ad will not be skipped

**Comment by dmunozv04** [comment]
Hello, I haven’t been able to reproduce the issue. Can you give more details about your setup? (os, python version, using docker…)

**Comment by dmunozv04** [comment]
Unable to reproduce
