### ISSUE TITLE
Adding Google Cloud API key for YouTube causes crash

### ISSUE THREAD

**Issue by Nezteb** [dmunozv04/iSponsorBlockTV#121]
**Describe the bug**
When running [the `docker run` command from the docs](https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation#step-1-create-a-config-file) to generate a config, this happens:

```
❯ docker run --rm -it \
    -v .:/app/data \
    ghcr.io/dmunozv04/isponsorblocktv \
    --setup-cli
Could not load config file
Blank config file created
Welcome to the iSponsorBlockTV cli setup wizard
Paired with 0 Device(s). Add more? (y/n) y
Enter pairing code (found in Settings - Link with TV code): REDACTED
Pairing...
Paired device: YouTube on TV
Paired with 1 Device(s). Add more? (y/n) n
API key only needed for the channel whitelist function. Add it? (y/n) y
Get youtube apikey here: https://developers.google.com/youtube/registering_an_application
Enter your API key: REDACTED
Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    helpers.app_start()
  File "/app/iSponsorBlockTV/helpers.py", line 128, in app_start
    config_setup.main(config, args.debug)
  File "/app/iSponsorBlockTV/config_setup.py", line 59, in main
    config["apikey"] = apikey
    ~~~~~~^^^^^^^^^^
TypeError: 'Config' object does not support item assignment
```

**Expected behavior**

No crash? 😅 

**iSponsorBlockTV server (please complete the following information):**
 - OS: macOS 14.2 (arm64)

**Apple TV (please complete the following information):**
 - Device: Sony Bravia 4K VH21
 - OS: Android TV OS 10
 	- Kernel: `4.19.75 #1 Thu Nov 2 10:49:42 JST 2023`
	- Build: `BRAVIA_VH21_UC-user 10 QTG3.200305.006.S362 674801 release-keys`

**Screenshots**

My Google Cloud console credentials page:
<img width="1276" alt="screenshot_2023-12-28_at_17 30 03@2x" src="https://github.com/dmunozv04/iSponsorBlockTV/assets/3588798/0c2d260a-ceda-49b6-9ec6-69b4f9fc23b6">

**Comment by dmunozv04** [comment]
Hi there, thanks for reporting the issue. I've managed to fix it and will push a new version soon. In the meantime, you could manually edit the `config.json` file that will be created on the `data_dir` directory or use the TUI setup wizard, which shouldn't have this problem (replace `--setup-cli` with `--setup` on your docker run command
