### ISSUE TITLE
Not skipping ads

### ISSUE THREAD

**Issue by VivienARI** [dmunozv04/iSponsorBlockTV#13]
Hello,

I'm running the docker version and python version of Isponsor on a debian 10 but it's not working on my apple TV.

Peering is ok with my apple TV on TVOS 15.0, Isponsor seems ok: 
starting
Discovering devices on network...
Connecting to X.X.X.X
Push updater started

When I start a youtube video, I have adds but on my computer with Isponsor I can see codes like that appear 8F2s8ivKXNY and on my API interface I can see the requests: 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/60771791/158590105-80425736-16b7-4313-9457-256f02901572.png">

Am I wrong somewhere? 

Or can I get more logs to debug this issue?

Thanks in advance,

Regards.

**Comment by dmunozv04** [comment]
Hello, that's really weird. However, seeing those codes is good, because they are youtube video ids. 
Could you send me the videos you tried and also test to play [this video](https://youtu.be/IZeOmEy-tE8)?

**Comment by dogotcat05** [comment]
Hi,
I have the app running in docker. In the logs it shows the following:
starting
Discovering devices on network...
Connecting to 192.168.1.196
Push updater started

However no sponsors are being skipped. Am I missing something here. Have updated the config.json with the correct values.

**Comment by dmunozv04** [comment]
Could you test with the video that I sent on the previous comment, please?

**Comment by dogotcat05** [comment]
Hi there,

I did that and nothing happened. Just played the sponsored section….

With the YouTube key, do we simply create one in the credentials section of the google console  and place that in the config.json?

**Comment by dmunozv04** [comment]
Looks weird. You should just put it there and it should work. 
Are you seeing any more logs after the Push updater started thing?
You should see some codes like you said on the first message. 
One thing, what "skip_categories" do you have on the config.json file?

**Comment by dogotcat05** [comment]
All is see is the message I posted above. Nothing when I play YouTube videos.

I have "skip_categories": ["sponsor”] in my config.

**Comment by dmunozv04** [comment]
That may be because the container had issues with disconnects in the past. Can you give it a restart: `docker restart iSponsorBlockTV `. It then it works, you can update it to the latest version

**Comment by dogotcat05** [comment]
Restarted the docker. Unfortunately still doesn’t work. Tested then with the LTT video from your example.

**Comment by dogotcat05** [comment]
Hi, is this how my config.json should look like for skipping categories? I have the app up and running but not skipping anything.

"skip_categories": ["sponsor", "selfpromo", "exclusive_access", "intro", "outro", "preview", "filler"]}

**Comment by dmunozv04** [comment]
Is this the full config file? If that’s the case it isn’t skipping any ads because there aren’t any apple TV’s there.

**Comment by dmunozv04** [comment]
It it’s another error, please run with debug enabled and send me the output. Run:
``` 
docker run --rm -it \
--network=host \
-v /PATH_TO_YOUR_CONFIG.json:/app/config.json \
ghcr.io/dmunozv04/isponsorblocktv \
--debug 
```

**Comment by dogotcat05** [comment]
[_strange_shtern_logs.txt](https://github.com/dmunozv04/iSponsorBlockTV/files/8549356/_strange_shtern_logs.txt)

The above was just a snippet I took out to show you. The rest of the config.json has the data in it.

**Comment by dmunozv04** [comment]
This suggests that it should work but I’m unable to work with such little data. Could you please send a full log dump when playing a video that should have sponsor segments on it? Also, make sure that you have updated to the latest docker version

**Comment by dschoorisse** [comment]
I think I have the same problem. In the console output and I can see which video is playing and its position, but sponsor segments are not skipped. 
[console output.txt](https://github.com/dmunozv04/iSponsorBlockTV/files/8744714/console.output.txt)

**Comment by dschoorisse** [comment]
Sorry, solved my issue. I had an Youtube API key, but the API was not enabled yet. It's working now! 👍

**Comment by dmunozv04** [comment]
Closed for being stale
