### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by purevertigo** [dmunozv04/iSponsorBlockTV#14]
How do I install in Windows?

**Comment by dmunozv04** [comment]
I haven’t tested it on windows, but you should be able to. install docker and follow the rest of the instructions without too many problems

**Comment by KennethWussmann** [comment]
Be aware that host networking, which is suggested by the installation guide, is not available on Windows Docker.

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.
https://docs.docker.com/network/host/

**Comment by dmunozv04** [comment]
Closed for being stale
