### ISSUE TITLE
VIDAA support (Hisense)

### ISSUE THREAD

**Issue by framebassman** [dmunozv04/iSponsorBlockTV#165]
Do you have any plans to support VIDAA TV OS?

**Comment by dmunozv04** [comment]
If it has a YouTube TV app, it should just work. Let me know if it does since I don’t have a device to test

**Comment by Thomahawkuru** [comment]
Can confirm Hisense Vida OS works when manually connecting using the link code. Autodiscovery has not worked for me, but seems like an unrelated cause (chromecast V2 was also not discovered)
