### ISSUE TITLE
Docker. Problem with adding new devices

### ISSUE THREAD

**Issue by whyyouhateme** [dmunozv04/iSponsorBlockTV#173]
UPD 
I’m sorry, it’s my mistake, I’m a fool and forgot to use the -it flag.

**Bug description**.
When I try to run the "--setup-cli" command, I get an error like "EOFError: EOF when reading a line"

**Replay**.
1. Connect via SSH
2. Run the command "docker exec iSponsorblockTV python3 -u main.pyc --setup-cli"
3. See the error

**Screenshots**.
![image](https://github.com/dmunozv04/iSponsorBlockTV/assets/154468298/b2a3dec2-0a16-472c-9cd9-c59bcbcb0c1b)

Server **iSponsorBlockTV:**.
 - OS: Synology DSM 7.1
 - Docker (Python 3.11.9)

**Comment by whyyouhateme** [comment]
I’m sorry, it’s my mistake, I’m a fool and forgot to use the -it flag.

**Comment by dmunozv04** [comment]
Oh, don’t worry. That’s good to know. Glad you figured it out!
