### ISSUE TITLE
SSL error in data received

### ISSUE THREAD

**Issue by chansonnier** [dmunozv04/iSponsorBlockTV#18]
Hi, great work, just super excited to see this in action. It seems my setup *is* detecting sponsor segments, but I'm getting an error. Hopefully this is helpful:

> SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x10e95eac8>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

For what it's worth, from my searching around, I found "SSL error in data received" popping up for others in a separate project here https://github.com/matrix-org/pantalaimon/issues/10#issuecomment-490605510. Not sure if what they're saying there about python 3.8 is helpful, but thought I might share that.

**To Reproduce**
1. Run main.py after ensuring dependencies are available and adding credentials, yt api key, and atv identifier to config.json
2. Pick some new L*nus tech tips video as that youtuber seems to be pretty much *all* sponsor (matter of fact, SponsorBlock has a new feature that labels the latest video of his as "entirely [sponsor] category"
3. See error (any time a sponsor segment is reached on the ATV)

**Expected behavior**
Segment skipped

**Screenshots**
N/A

**iSponsorBlockTV server (please complete the following information):**
 - OS: macOS 11.4
 - Python version 3.7

**Apple TV (please complete the following information):**
 - Device: Apple TV 4k 2nd gen
 - OS: tvOS 15.3

**Additional context**
N/A

**Comment by dmunozv04** [comment]
Hi, this may be a system python error. I'd suggest installing python from [brew](https://brew.sh). `brew install python@3.10`

Then instead of using python as the command use: `$(brew --prefix)/opt/python@3.10/libexec/bin/python`
It should work that way

**Comment by dmunozv04** [comment]
Hello, I have implemented a new native macOS install method. Can you give it a try?

**Comment by dmunozv04** [comment]
Yes, that would be great. Thanks for the quick response
