### ISSUE TITLE
Docker Installation error

### ISSUE THREAD

**Issue by dogotcat05** [dmunozv04/iSponsorBlockTV#19]
Before opening an issue make sure that there are no duplicates and that you are on the latest version. 
When I run the Docker command to install I get this error when trying to add my Apple TV to the config.json in the new docker setup procedure.
---

Found Living Room. Do you want to add it? (y/n) y
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/pyatv/protocols/airplay/auth/hap.py", line 43, in start_pairing
    await self.http.post("/pair-pin-start", headers=_AIRPLAY_HEADERS)
  File "/opt/venv/lib/python3.10/site-packages/pyatv/support/http.py", line 359, in post
    return await self.send_and_receive(
  File "/opt/venv/lib/python3.10/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/create_config.py", line 105, in <module>
    main()
  File "/app/create_config.py", line 64, in main
    loop.run_until_complete(task)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/app/create_config.py", line 42, in find_atvs
    await pairing.begin()
  File "/opt/venv/lib/python3.10/site-packages/pyatv/protocols/airplay/pairing.py", line 62, in begin
    return await error_handler(
  File "/opt/venv/lib/python3.10/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: HTTP/1.1 method POST failed with code 400: Bad Request
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb37a81f0>

--

**To Reproduce**
Docker command that I ran:
docker run --rm -it \
--network=host \
--entrypoint /opt/venv/bin/python3 \
-v /home/pi/config.json:/app/config.json \
ghcr.io/dmunozv04/isponsorblocktv \
/app/create_config.py

**Expected behavior**
Adding the Apple TV correctly to the config.json file.

**Screenshots**

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker on Pi 64 headless
 - Python version [e.g. 3.7] (no need to fill if running on docker

**Apple TV (please complete the following information):**
 - Device: Latest Apple TV 4K
 - OS:  15.4

**Additional context**

**Comment by dmunozv04** [comment]
Hi, could you try to obtain the credentials manually?

Steps:
```
docker run --rm -it --network=host --entrypoint /bin/bash ghcr.io/dmunozv04/isponsorblocktv
atvremote scan
atvremote pair --protocol airplay --id <identifier you got on the previous step>
exit the container
```

**Comment by dmunozv04** [comment]
Also, make sure that the option to connect to apple TV's in the home app is set to allow anyone from this network.

**Comment by theprinceofspace** [comment]
yep that is set. connected the ATV and API key. does this mean setup is done and I should run the other command? 

Push updater started

**Comment by theprinceofspace** [comment]
looks like it installed ok but now I see a restart loop in docker. the fun isnt over yet!

<img width="685" alt="Screen Shot 2022-04-20 at 12 44 37 PM" src="https://user-images.githubusercontent.com/103888720/164281544-146a9dc9-a6ac-4b30-bc3f-7eacdae4156e.png">

**Comment by dmunozv04** [comment]
Can you provide the command you ran and the logs that docker is outputting?

**Comment by theprinceofspace** [comment]
```
docker pull ghcr.io/dmunozv04/isponsorblocktv
docker run -d \
--name iSponsorBlockTV \
--restart=unless-stopped \
--network=host \
-v /volume1/docker/isponsorblocktv/:/app/config.json \
ghcr.io/dmunozv04/isponsorblocktv
```

**Comment by dmunozv04** [comment]
Can you provide the logs that docker is outputting?

**Comment by theprinceofspace** [comment]
sorry, still trying to track those down.

**Comment by theprinceofspace** [comment]
So. there appear to be no logs. running this for sponsorblocktv has no results but other docker containers have huge logs. 
docker logs 55b770970182

**Comment by dmunozv04** [comment]
> Hi, could you try to obtain the credentials manually?
> 
> Steps:
> 
> ```
> docker run --rm -it --network=host --entrypoint /bin/bash ghcr.io/dmunozv04/isponsorblocktv
> atvremote scan
> atvremote pair --protocol airplay --id <identifier you got on the previous step>
> exit the container
> ```

@dogotcat05
