### ISSUE TITLE
Autoplay on with no way to disable it (off in settings)

### ISSUE THREAD

**Issue by theprinceofspace** [dmunozv04/iSponsorBlockTV#190]
A couple weeks ago, Youtube on my Apple TV started Auto Playing videos. Only when iSponsorBlockTV is connected. This never happened before. Autoplay is off in the YT settings. 

At the end of a video, there is a 5 second countdown which says "To cancel press stop on your mobile device"

**Comment by dmunozv04** [comment]
It looks like you updated to v2.1.0, which now includes a new config setting: `auto_play`. It has to be manually set to `false` to prevent autoplay from working. If you want context as to why this setting was added, check #82

**Comment by theprinceofspace** [comment]
Thanks, reran config and turned off autoplay. All good here.
