### ISSUE TITLE
Wiki - minor fix

### ISSUE THREAD

**Issue by notDavid** [dmunozv04/iSponsorBlockTV#202]
Hi, i was just reading [this section of the Wiki](https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation), it's a little confusing when first read. It lists:

```
# Step 1
## option 1
## option 2
## option 1
## option 2
## option 3
```

Is this supposed to be... ? :

```
# Step 1
## option 1
## option 2
# Step 2
## option 1
## option 2
## option 3
```

I assume Step 2 is simply running the container...

Would be nice if you can clarify / fix, to prevent confusion.

Thank you!

**Comment by dmunozv04** [comment]
Thanks for opening an issue, it appears that in some revision of the wiki article, that section title got lost. I've added it back. Thanks!
