### ISSUE TITLE
Add Youtube Data API to requirement

### ISSUE THREAD

**Issue by L041S** [dmunozv04/iSponsorBlockTV#24]
Hello,
For people that are not familiar with the Google Cloud Platform I think it could be helpful to specify the necessity to add "Youtube Data API" with the project created to get API keys. 

During the setup, the installer redirects to a Google Page explaining how to get an API key but nothing about the YT API.
Maybe an extra line saying "Don't forget to add Youtube Data API to your project" ?

It may appear silly but it was the first time I used the google platform and I stupidly lost an hour searching why iSponsorBlockTV didn't worked on my Apple TV x)

Otherwise everything works perfectly, thank you for the project !

**Comment by ivangohub** [comment]
hi there, I set this up on my Mac and it worked(successfully paired to my appletv. and successfully skipped ads)but after a while(about 10mins)it didn't work anymore.  so I turn to my router(an openwrt)and set up the docker version sadly it didn't work totally. I checked the Youtube data api it shows 
youtube.api.v3.V3DataSearchService.List |quests  867 | Errors 87.89%
idk why this happening  maybe something wrong between the SponsorBlock API and youtube api?

**Comment by dmunozv04** [comment]
Please run the application with `—debug`

**Comment by CDeLeon94** [comment]
> "Youtube Data API"

I had a little of experience with their platform, but still wasn't sure which API access needed to be enabled and optionally bound to the API key for extra security.

**Comment by dmunozv04** [comment]
Closed for being stale
