### ISSUE TITLE
Could not find video id

### ISSUE THREAD

**Issue by L041S** [dmunozv04/iSponsorBlockTV#25]
Hello,
The tool is working fine but on some videos, sponsored messages don’t get skipped. I checked the logs and it seems that the error "Could not find video id" is the problem.

For exemple it works with this video of Linus https://youtu.be/BtFdraQWVtM but not this one from Nozman https://youtu.be/A66mibBBAoo

**Comment by Garciasergio** [comment]
I have the same problem

**Comment by dmunozv04** [comment]
Please attach logs/device details

**Comment by mvicari** [comment]
I'm having the same issue

Could not find video id
Could not find video id
ZteAovHJllk
[{'start': 0, 'end': 4.2, 'UUID': ['5378f6709b14e39c814c8aff035fd48ce29ccd1d0c92e23b5d598db64d965c19d']}, {'start': 1212.709, 'end': 1283.594, 'UUID': ['59052147dd66c4a6b8f656a3fdb355d0e99be623155ae02d82eefaa491a4cd0d5']}]

**Comment by dmunozv04** [comment]
The last 2 lines suggest that it is indeed working and finding the video id and the segments to skip correctly

**Comment by dmunozv04** [comment]
This video is known to work: [https://youtu.be/BtFdraQWVtM](https://youtu.be/BtFdraQWVtM)
Please try with it and let me know if it does work

**Comment by wayou** [comment]
still id not found :(

**Comment by pkarpovich** [comment]
Hi there,

I recently experienced the same error you reported. I traced the issue to this line in the code: https://github.com/dmunozv04/iSponsorBlockTV/blob/1aa06e677f4d1f30da11f86f5ba30cc91b019efc/iSponsorBlockTV/api_helpers.py#L26

The YouTube API returned an error message stating, "YouTube Data API v3 has not been used in project XXX before or it is disabled. Enable it by visiting...". This seems to be the underlying cause for the subsequent 'Could not find video id' issue.

I want to propose enhancing API error handling. Could we print these error messages directly to the console? This might streamline the debugging process and help prevent similar misunderstandings in the future.

Looking forward to hearing your thoughts.

**Comment by wayou** [comment]
Enable the API seems working. Now there's only several "id not found" errors.  Maybe we can print the guide to the console [YouTube Data API Overview](https://developers.google.com/youtube/v3/getting-started).

**Comment by SystemZ** [comment]
Just FYI for users from search engine.
After creating API key, make sure you enabled YouTube Data API v3 at this URL and make sure you selected correct Project in GCP console
https://console.cloud.google.com/apis/library/youtube.googleapis.com

**Comment by dmunozv04** [comment]
Closed due to being stale and V2 overhauling
