### ISSUE TITLE
Add support for whitelistedChannels configuration

### ISSUE THREAD

**Issue by nocturne1** [dmunozv04/iSponsorBlockTV#26]
Sponsorblock itself has a "whitelistedChannels" configuration that allows certain channels to not have skipped ads. From what I can tell, this project doesn't support this at the time. As a handful of channels surprisingly have entertaining ads, I'd love to have this feature. Any plans, or am I just attempting to configure it the wrong way? For example, I tried adding just below skip_categories, as some of the browser extensions allow:

    "skip_categories": ["sponsor"],
    "whitelistedChannels":["agingwheels","3Dbotmaker"]

**Comment by dmunozv04** [comment]
It hasn’t been implemented, feel free to make a PR and implement it yourself
