### ISSUE TITLE
A way to have it automatically update and pull new info from the sponsorblock server?

### ISSUE THREAD

**Issue by ghstzch** [dmunozv04/iSponsorBlockTV#27]
Is there a way currently to have it pull new data automatically once a day instead of manually rebooting the docker container?

**Comment by dmunozv04** [comment]
As you can see [here]( https://github.com/dmunozv04/iSponsorBlockTV/blob/main/iSponsorBlockTV/api_helpers.py#L33) , segments are only cached for 300 seconds, which is five minutes. Is that what you mean as pulling new data?

**Comment by dmunozv04** [comment]
Hi, the video lookup is set to store the 10 latest seen videos, but it could be modified to request new video ID's periodically.

**Comment by dmunozv04** [comment]
Closed for being stale
