### ISSUE TITLE
Hmm doesnt seem to work here

### ISSUE THREAD

**Issue by joeblack2k** [dmunozv04/iSponsorBlockTV#28]
Hey,

it doesn't seem to skip anything i tested it with 10+ videos from LTT 

`
{"atvs": [{"identifier": "58:D3:49:CC:0E:25", "airplay_credentials": "63ab822772c306fd1623811ac0a3a99a1c....."}, {"identifier": "EC:A9:07:14:61:60", "airplay_credentials": "d641c673b0c2021b36933b7c0357e7d....."}, {"identifier": "40:CB:C0:B2:DE:D1", "airplay_credentials": "0b0117987330c8ac69c2047b679cd71...."}], "apikey": "AIzaSyAkexkdL....", "skip_categories": ["sponsor,", "selfpromo,", "exclusive_access,", "interaction,", "poi_highlight,", "intro,", "outro,", "preview,", "filler,", "music_offtopic"]}
`

Anything i could do to help?

**Comment by dmunozv04** [comment]
Yes, for some reason the new configurator adds a , to every category:
Until I fix it, try removing the , form each category
Example: `"skip_categories": ["sponsor", "selfpromo", "exclusive_access", "interaction", "poi_highlight", "intro", "outro", "preview", "filler", "music_offtopic"]}`

**Comment by joeblack2k** [comment]
Works! omg i feel so stupid i didnt see that myself!

awesome!
