### ISSUE TITLE
Identifying ATV on network fails

### ISSUE THREAD

**Issue by benklinger** [dmunozv04/iSponsorBlockTV#29]
Installed via Docker on MacOS.
Using pyatv, I found my ATV identifier:
`04:4B:ED:99:FB:XX`

I then used pyatv to find the airplay_credentials:
`d6683fd0d2bdfca0926bfd5366b4f07191a9566fb8da04f3c03e90e76f544fc3:3a870e73c4621966cb3dadada32cc8d7e5c777f38efb9fe523118b79f699c413:36323839413335382d343336312d343945392d414442332d454241333046303144424239:39386336373835632d666330332d343463352d386561362d3337626639306637656162XX`

I've updated the config.json file with these two inputs, but after restarting the docker, this is the logs I see:
```
Discovering devices on network...
No device found, will retry
Reconnecting to Apple TV
Discovering devices on network...
```

**Comment by dmunozv04** [comment]
That is caused due to docker in macOS not having --net=host mode, which is needed for pyatv to work in docker. 

From docker's documentation:```
The host networking driver only works on Linux hosts, and is not supported on Docker for Mac, Docker for Windows, or Docker EE for Windows Server.
```
The solution is using the iSponsorblockTV macOS service. It runs as a regular macOS app

**Comment by benklinger** [comment]
I ran into other issues there. this line:
```wget https://github.com/dmunozv04/iSponsorBlockTV/releases/latest/download/iSponsorBlockTV```

leads to a 404

**Comment by dmunozv04** [comment]
Thank you, I'll update it later

**Comment by dmunozv04** [comment]
fixed
