### ISSUE TITLE
Failure to Launch - not sure if it is a bug

### ISSUE THREAD

**Issue by c0d3-n00b** [dmunozv04/iSponsorBlockTV#30]
Hi there - I see this error while attempting to launch the plist:

launchctl load ~/Library/LaunchAgents/com.dmunozv04.iSponsorBlockTV.plist

Error:

Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

Has anyone else run into this error?

Thanks!

**Comment by dmunozv04** [comment]
This will be fixed with #108
