### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Striker72rus** [dmunozv04/iSponsorBlockTV#31]
Hi!

Docker run in NAS:

DEBUG:pyatv.core.protocol:Dispatching message with type 4 to <bound method PlayerStateManager._handle_set_state of <pyatv.protocols.mrp.player_state.PlayerStateManager object at 0x7f4bb4936d10>>
DEBUG:pyatv.auth.hap_channel:Sending data (Encrypted=200072c79fc370115f795734f7e04b797d6aced895e865da4a74a432df46d781564d0c90e737a5f8039fa300229ef94d86ac)
DEBUG:root:App playing is:com.google.ios.youtube
DEBUG:pyatv.core.protocol:Dispatching message with type UpdatedState.Playing to <bound method FacadePower._playing_changed of <pyatv.core.facade.FacadePower object at 0x7f4bb4936980>>
DEBUG:root:Playstatus update  Media type: Unknown
Device state: Playing
      Repeat: Off
     Shuffle: Off
DEBUG:root:App playing is:com.google.ios.youtube
DEBUG:asyncio:<asyncio.sslproto.SSLProtocol object at 0x7f4bb4937fa0>: SSL error in data received
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 206, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/local/lib/python3.10/ssl.py", line 979, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2672)

**Comment by dmunozv04** [comment]
Please try again with the latest version

**Comment by dmunozv04** [comment]
Should be solved with v2
