### ISSUE TITLE
MacOS Install Error 

### ISSUE THREAD

**Issue by KTsarlz** [dmunozv04/iSponsorBlockTV#33]
Following the installl instructions in the wiki, I'm getting the no such file or directory error

![ScreenShot 2022-10-08 at 17 00 16](https://user-images.githubusercontent.com/9140507/194699432-eaa72f26-e013-4996-9b59-31726f9f89ad.png)

**Comment by KTsarlz** [comment]
Also getting this 

➜  ~ chmod +x iSponsorBlockTV
➜  ~ ./iSponsorBlockTV --macos_install
zsh: permission denied: ./iSponsorBlockTV
➜  ~ su ./iSponsorBlockTV --macos_install
Password:
su: Sorry
➜  ~

**Comment by dmunozv04** [comment]
Replace the wget command with the following one (now updated in the wiki)
`curl https://github.com/dmunozv04/iSponsorBlockTV/releases/download/v0.1/iSponsorBlockTV-macos -o iSponsorBlockTV `

**Comment by dmunozv04** [comment]
This will be fixed by #108
