### ISSUE TITLE
Docker setup, can't find Apple TV 2022 on iOS 16.2

### ISSUE THREAD

**Issue by reversed95** [dmunozv04/iSponsorBlockTV#38]
**Describe the bug**
During the setup the prompt returns 0 Apple TV's found.

**iSponsorBlockTV server (please complete the following information):**
Docker on UNRAID

**Apple TV (please complete the following information):**
Apple TV 2022, OS 16.2

**Comment by dmunozv04** [comment]
I’m going to need more information since I don’t have an unraid machine to replicate.
First, please run with the `--debug` flag and provide the logs.
Second, provide the exact docker command you used to run iSponsorBlockTV.

**Comment by dmunozv04** [comment]
Also, I just realized it’s a 2022 apple TV, this has already been reported. https://github.com/dmunozv04/iSponsorBlockTV/issues/36

**Comment by reversed95** [comment]
Yeah I'm sorry, didn't check the closed tickets. Thanks for the quick response.

**Comment by dmunozv04** [comment]
No problem, please wait a bit while the new build (that should fix the issue) gets uploaded. Please report if it does work

**Comment by dmunozv04** [comment]
I'll close the issue soon if I don't get an answer confirming the fix

**Comment by reversed95** [comment]
Hi dmunozv04,

I'm sorry for the late response, but I've managed to add the Apple TV manually using the atvremote command. However, the skipping doesn't seem to work. It might be because it is running on unRAID. I will try to dig a bit deeper. Cheers.

**Comment by dmunozv04** [comment]
I haven’t used unRAID, but make sure you start the container with `--net=host` https://wiki.unraid.net/Manual/Docker_Management#Network_Type

**Comment by reversed95** [comment]
Yes I have done that. Here is the overview of the container running in Docker
<img width="738" alt="iSponsorBlockTV 1" src="https://user-images.githubusercontent.com/33935450/220934989-be421307-bf69-496c-b082-3f3cf1fe0f36.png">

And here is the log
<img width="209" alt="iSponsorBlockTV 2" src="https://user-images.githubusercontent.com/33935450/220935009-d8273cf4-4f59-4ea5-9bc7-0fa1de2cb210.png">

**Comment by reversed95** [comment]
No new logs are generated unfortunately. Should the DNS server of the Apple TV be the IP address of the server? Thanks in advance.

**Comment by dmunozv04** [comment]
You shouldn’t need to change the dns server. Please get the latest version with `docker pull ghcr.io/dmunozv04/isponsorblocktv ` and try to add the Apple TV again

**Comment by dmunozv04** [comment]
This should be “fixed” with V2, since it connects to devices using a different protocol
