### ISSUE TITLE
[Troubleshooting] Runs but doesn't skip sponsor segments.

### ISSUE THREAD

**Issue by systox** [dmunozv04/iSponsorBlockTV#43]
---
name: Troubleshooting Request
about: Create a report to help us improve.
labels: Bug vs User Error

---

iSponsorBlockTV Latest Version?:
Confirmed, I am on the latest version as of typing this.

**Describe the bug**
This is my first install. I used pyatv and the first time setup to complete the config.json. The script runs and looks like its working in windows. But no sponsor segments are skipped. I tried rebooting the computer its installed on, rebooting the apple tv, and trying multiple newer and older videos on youtube.

**iSponsorBlockTV server (please complete the following information):**
 - OS: [Windows 10]
 - Python version [3.11]

**Apple TV (please complete the following information):**
 - Device: [Apple TV 4K 3rd generation 128 GB (2022)]
 - OS: [e.g. tvOS 16.4.1]

**Additional context**
--debug logs (some info obfuscated):
https://pastebin.com/XHDHCGGz

**Comment by dmunozv04** [comment]
Hello, line 1225 of your logs `DEBUG:asyncio:Get address info www.googleapis.com:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 1024> ` suggests that at least the connection to the youtube api is working. Do you have a google api key with access to the youtube data api v3 on your config file?

**Comment by systox** [comment]
Thanks for looking into this. 

I have a google API key but i'm not sure about access to the youtube data api V3? 

I went to https://console.cloud.google.com/apis, clicked create credentials, and then clicked "API Key". Not sure if I'm missing steps; looking into it more.

**Comment by dmunozv04** [comment]
Obtaining authorization credentials  |  YouTube Data API  |  Google Developersdevelopers.google.comThis should help you get the api key working correctly Message ID: ***@***.***>

**Comment by dmunozv04** [comment]
Thanks for your comment!
