### ISSUE TITLE
Docker full support

### ISSUE THREAD

**Issue by dmunozv04** [dmunozv04/iSponsorBlockTV#5]
Docker currently works but it isn't perfect. List of issues (saving this here for future me)

- [x] Armv7 isn't supported

- [x] #8

- [x]  Docker doesn't print any logs

**Comment by dogotcat05** [comment]
Hi, how far away are we with arm support. Would love to run this in docker on my pi.

**Comment by dmunozv04** [comment]
> Hi, how far away are we with arm support?. Would love to run this in docker on my pi.

You can run it on your Pi if you use the 64 bit piOS image

**Comment by dogotcat05** [comment]
Im running homebridge os on my pi. I believe this is 32 bit. headless  :(

**Comment by dmunozv04** [comment]
@dogotcat05 arm 32 bit should work now
