### ISSUE TITLE
Will there be an update that recognizes new Apple TVs automatically?

### ISSUE THREAD

**Issue by ghstzch** [dmunozv04/iSponsorBlockTV#51]
No matter what I try, and have followed the instuctions that previous people gave to fix, I can't get this to work with my ATV 4k 3rd gen. 

Will there be a new release of this package so it includes all the new fixes?

**Comment by dmunozv04** [comment]
The latest fix should recognize it since it filters by OS instead of filtering by Apple TV model. Try manually pulling the latest version of the container with `docker pull ghcr.io/dmunozv04/isponsorblocktv` and please let me know if you can add you new Apple TV after that

**Comment by ghstzch** [comment]
I will try this and report back. Thanks for the quick and helpful response as always, David!

**Comment by ghstzch** [comment]
> macabus:/volume1/docker/isponsorblocktv# docker pull ghcr.io/dmunozv04/isponsorblocktv:buildcache
buildcache: Pulling from dmunozv04/isponsorblocktv
manifest unknown
macabus:/volume1/docker/isponsorblocktv# docker pull ghcr.io/dmunozv04/isponsorblocktv:buildcache
buildcache: Pulling from dmunozv04/isponsorblocktv
manifest unknown
macabus:/volume1/docker/isponsorblocktv# docker pull ghcr.io/dmunozv04/isponsorblocktv
Using default tag: latest
latest: Pulling from dmunozv04/isponsorblocktv
8a49fdb3b6a5: Pull complete 
0357922e53aa: Pull complete 
9676b6d4b964: Pull complete 
ddbd03ee1059: Pull complete 
877a053836a3: Pull complete 
974703e674b4: Pull complete 
a2b47a368e2e: Pull complete 
1f6ffcc1f026: Pull complete 
4f4fb700ef54: Pull complete 
b9568252c679: Pull complete 
ab3fdf546277: Pull complete 
Digest: sha256:15f150c2ca6360af579952ac695ff6f92669e6c1fb5a28f2fc256fd9916470ed
Status: Downloaded newer image for ghcr.io/dmunozv04/isponsorblocktv:latest
ghcr.io/dmunozv04/isponsorblocktv:latest
macabus:/volume1/docker/isponsorblocktv# docker run --rm -it \
> --network=host \
> -v /volume1/docker/isponsorblocktv/config.json:/app/config.json \
> ghcr.io/dmunozv04/isponsorblocktv \
> --setup
Creating config file
Found 0 Apple TV(s) in config.json. Add more? (y/n) y
Done adding
Get youtube apikey here: https://developers.google.com/youtube/registering_an_application
Enter your API key: 



I tried adding via the buildcache and that gave an error. Tried downloading the new image directly and it's still not seeing the ATV during the setup. If I go in manually and scan with atvremote scan, it sees it on the network and lets me pair. But when I add the credentials to the config file, the container doesnt recognize it and tells me to create a config file with --setup.

**Comment by dmunozv04** [comment]
I don’t have a 3rd gen Apple TV to investigate myself, but if you are able to get the credentials manually, make sure that you’re following the latest [template](https://github.com/dmunozv04/iSponsorBlockTV/blob/main/config.json.template) for the config file, you are most likely missing the entry `"channel_whitelist": [] `

**Comment by ghstzch** [comment]
Here it is. 

> "atvs": [{"identifier": "330C...", "airplay_credentials": "ae04..."}],"apikey":"AIza...", "skip_categories": ["sponsor", "selfpromo", "intro", "outro"],"channel_whitelist": []

When I run the docker container with the config file in place I get this error, which I have got many times before when I've tried to get it working. Not sure what I am doing wrong. :( 

> Creating config file
invalid config file, please run with --setup
Creating config file

**Comment by oxixes** [comment]
Please run the setup again, as not too long ago the structure of the settings file was changed. Alternatively add `"channel_whitelist": []` to the root object of the JSON, as that is most likely the problem.

**Comment by dmunozv04** [comment]
You might be missing the opening and closing brackets on the file, format it like this:
```json
{
   "atvs": [
      {
         "identifier": "330C...",
         "airplay_credentials": "ae04..."
      }
   ],
   "apikey": "AIza...",
   "skip_categories": [
      "sponsor",
      "selfpromo",
      "intro",
      "outro"
   ],
   "channel_whitelist": []
}

```

**Comment by ghstzch** [comment]
Making some good progress here! Thank you both for all the help.

> Discovering devices on network...
Connecting to 192.168.1.84
Push updater started
Could not find video id
ID: YLC9rZ2e0Ms, Channel ID: UCXuqSBlHAE6Xw-yeJA0Tunw
[{'start': 0, 'end': 3.107, 'UUID': ['9ce3044ca92e0d133fb8dd8976ec25cd209d02d014577da158074c1940dcde0b6']}, {'start': 40.687, 'end': 61.463, 'UUID': ['5692b4e69e78cf161afaacad6ff9d274671dd17d051c439531df02f7d13f552c6']}, {'start': 513.536, 'end': 561.285, 'UUID': ['71db74461bb4d4de36be2140c7b7deccf3d8b0b303b7b08c87f5a6c81a6a085d6']}, {'start': 1115.055, 'end': 1125.778, 'UUID': ['295bcdcb3c610fd6fec89c231eaf478e95f151432f78ce0fa155c141db5da25b6']}, {'start': 1223.336, 'end': 1234.961, 'UUID': ['1e0a87cabaa0a2e20ea2078f94dfe3a0c0f1ad8345254fe220c45bd5fec88bd96']}]

It is at least pulling data now. I noticed it didn't skip in this video but I will try restarting the apple tv and a few things and see if that works and do some more testing. 

Thanks again for this awesome application and helping me out.

**Comment by dmunozv04** [comment]
It looks like it’s working perfectly. Even if it sometimes shows `Could not find video id` , the fact that it got some segments means that it’s working
