### ISSUE TITLE
Nothing happens after last setup command

### ISSUE THREAD

**Issue by tonysprenk** [dmunozv04/iSponsorBlockTV#53]
**Describe the bug**
I run `./iSponsorBlockTV --macos_install` but after that nothing happens.

**Comment by oxixes** [comment]
Could you be a bit more specific on the steps you performed? Did you follow the guide at https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation#macOS?

**Comment by tonysprenk** [comment]
Yes I followed alle the steps as described in the wiki but nothing happens after the last step.

**Comment by oxixes** [comment]
Do you have an M1/M2 mac or an Intel mac?

**Comment by tonysprenk** [comment]
M2

**Comment by oxixes** [comment]
IIRC `iSponsorBlockTV ` was compiled for Intel macs only (Rosetta may not be working correctly). Also, that version is outdated, so it would be better to run directly from source. @dmunozv04 may have more information regarding this issue.

**Comment by dmunozv04** [comment]
Was the output of `./iSponsorBlockTV --macos_install` blank or did it show the configurator? 
Also please check if `~/Library/LaunchAgents/com.dmunozv04.iSponsorBlockTV.plist ` exists

**Comment by tonysprenk** [comment]
It was blank. Building from source worked. The file is there but not sure if that’s from building from source.

**Comment by tonysprenk** [comment]
If needed I can uninstall everything and do testing.

**Comment by dmunozv04** [comment]
If the launch daemon was there, it means that at least some part of the macOS install did work, but it failed at some point when loading the configurator for the first time

**Comment by dmunozv04** [comment]
This will be fixed by #108
