### ISSUE TITLE
why? what happend?

### ISSUE THREAD

**Issue by Yumega** [dmunozv04/iSponsorBlockTV#56]
my docker system support host mode
```
docker run -d \ 
--name=iSponsorBlockTV \ 
--restart=unless-stopped \
 --network=host \ 
 -v /opt/iSponsorBlockTV/config.json:/app/config.json \ 
-e PUID=0
-e PGID=0
ghcr.io/dmunozv04/isponsorblocktv 
--setup
```
get error
stderr: EOFError: EOF when reading a line
![image](https://github.com/dmunozv04/iSponsorBlockTV/assets/61570667/a39b63d5-a737-4921-a784-72f7258091f6)

**Comment by dmunozv04** [comment]
Are you running docker in a non-interactive terminal? That could break some stuff.
If you want, you can test the v2 branch, brand new. Use [these instructions](https://github.com/dmunozv04/iSponsorBlockTV/wiki/Migrate-from-V1-to-V2) to use the v2 branch

**Comment by dmunozv04** [comment]
@Yumega 0 devices found means that you haven’t added any. Please use the configurator as described on the v2 guide to add devices

**Comment by dmunozv04** [comment]
@Yumega It’s already nicely explained on the doc. Just run the docker command and it should open

**Comment by dmunozv04** [comment]
@Yumega no, just run the command and it should work. Append `--setup` to the command you ran earlier that gave you the no devices found error

**Comment by dmunozv04** [comment]
@Yumega did it work correctly?

**Comment by dmunozv04** [comment]
@Yumeg I've posted a new version. Please check it out and let me know if it fixes your issues

**Comment by dmunozv04** [comment]
You need to [run the configurator first](https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation#using-the-new-graphical-configurator-tool). This should be the command with your config directory mounted.
```Shell
docker run --rm -it \
--name iSponsorBlockTV \
--net=host \ # Remove line on windows and macOS
-v /opt/iSponsorBlockTV:/app/data \
ghcr.io/dmunozv04/isponsorblocktv \
--setup
```

**Comment by dmunozv04** [comment]
Did the command I sent on the previous comment open a configurator window for you to enter some data? If not, try the text-based configurator, it should avoid some issues with the other configurator
```Shell
docker run --rm -it \
--name iSponsorBlockTV \
--net=host \ # Remove line on windows and macOS
-v /opt/iSponsorBlockTV:/app/data \
ghcr.io/dmunozv04/isponsorblocktv \
--setup-cli
```

**Comment by dmunozv04** [comment]
V2 has changed some stuff. You need to go into YouTube -> Settings -> Link with code. There you should get a 12 digit code to input

**Comment by dmunozv04** [comment]
That's great to hear, you're welcome
