### ISSUE TITLE
GUI setup terminal colors

### ISSUE THREAD

**Issue by nol166** [dmunozv04/iSponsorBlockTV#61]
1. Go to `terminal.app` in macOS
2. Run the recommended docker command to use the GUI install

	```bash
	docker run --rm -it \
	-v {my_path}:/app/data \
	ghcr.io/dmunozv04/isponsorblocktv \
	--setup
	```
4. See difficult to read text due to lack of 256 color support

**Expected behavior**
GUI is visible in the default terminal in the OS without needing to enable additional colors. It looked normal when launching with iTerm2

**Screenshots**
![Screenshot 2023-10-13 at 10 02 32 PM](https://github.com/dmunozv04/iSponsorBlockTV/assets/5651438/63294d92-551a-4fcd-b6d0-602434eb17cc)

**iSponsorBlockTV server (please complete the following information):**
Docker instance running on M1 Mac Mini. Version 2.0.1

**Apple TV (please complete the following information):**
Apple TV 4k (2018ish)

**Additional context**
I also encountered the issue with not being able to exit the setup after entering the API key. The hotkey "S" doesn't seem to work. I was able to use the config file to that it created to run the app though.

**Comment by dmunozv04** [comment]
The people at textual provide [this FAQ answer](https://textual.textualize.io/FAQ/#why-doesnt-textual-look-good-on-macos) about textual apps looking bad on `terminal.app``, bit they shouldn’t look that bad. I’ll play with it because it might have to do with some env variables I set on the Dockerfile

**Comment by dmunozv04** [comment]
You could also use [the text-based configurator](https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation#using-the-text-based-cli-configurator-tool), which shouldn’t have any graphical issues

**Comment by dmunozv04** [comment]
adding `-e TERM=$TERM -e COLORTERM=$COLORTERM` to the docker run command seems to do the trick. I'll update the wiki later

**Comment by nol166** [comment]
Awesome! Ty. Small issue otherwise an amazing application

**Comment by dmunozv04** [comment]
Thanks!
