### ISSUE TITLE
Does not mute or skip ads on Samsung TV

### ISSUE THREAD

**Issue by heyjared** [dmunozv04/iSponsorBlockTV#65]
**Describe the bug**
YouTube ads are not muted and skipped.

**To Reproduce**
1. Play any video with ads  

**Expected behavior**
YouTube ads should be muted and skipped.

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker on linux Amd64 v2.0.1

**Apple TV (please complete the following information):**
 - Device: Samsung Q80T
 - OS: Tizen 

**Additional context**
Skips sponsorblock segments correctly

**Comment by dmunozv04** [comment]
Hi there, is the TV added to the list of devices on iSponsorBlockTV and the category of segments that you want to skip selected? 
You can check it easily by reading the config file. If you send it, please remove the `"screen_id": "",` section from every device before sharing; as that would allow a third party to control your TV
