### ISSUE TITLE
Doesn't appear to work on Onn TV bare metal

### ISSUE THREAD

**Issue by cgriffith99** [dmunozv04/iSponsorBlockTV#67]
I'm testing on an Onn Android TV device and it doesn't seem to be working, but I'm not quite sure if I have everything set up correctly.

I am running your app on my PC, have linked with a code (your app shows a device screen id for the Android TV device) and have gotten a YouTube Data API v3 key to associate. Is this correct? I couldn't find any step by steps for making sure I config this correctly

I tried a SponsorBlock video id that is in their database and it is still playing sponsored ads at the beginning, etc.

**Comment by jt3dst** [comment]
Same for me with a Nvidia Shield. 

Can see this in logs : 
Connected to device YouTube on TV
Playing h_uCO7FoZd8 with 0 segments
Getting segments for next video: F_e7a3rP0Pk
Playing h_uCO7FoZd8 with 0 segments
Playing h_uCO7FoZd8 with 0 segments
Getting segments for next video: h_uCO7FoZd8
Getting segments for next video: h_uCO7FoZd8
Playing h_uCO7FoZd8 with 0 segments
Playing h_uCO7FoZd8 with 0 segments
Getting segments for next video: F_e7a3rP0Pk
Connected to device YouTube on TV

**Comment by dmunozv04** [comment]
@jt3dst it seems to be working fine for you. As the logs say, you’re playing a video with 0 segments on the SponsorBlock database, so there’s nothing to skip. If you were expecting to skip YouTube ads, make sure that option is enabled on your config

**Comment by dmunozv04** [comment]
@cgriffith99 if it shows a device then it should be working. Do you mind sending logs of the container that show some device activity?

**Comment by jt3dst** [comment]
There is my config :

{
    "data_dir": "data",
    "devices": [
        {
            "screen_id": "xxxxxxovod66gqm2puomfn2r",
            "name": "YouTube on TV"
        }
    ],
    "apikey": "",
    "skip_categories": [
        "sponsor",
        "selfpromo"
    ],
    "channel_whitelist": [],
    "skip_count_tracking": true,
    "mute_ads": false,
    "skip_ads": true
}

But at the begining of videos i still have Ads

**Comment by dmunozv04** [comment]
@jt3dst unfortunately, only ads that show a `skip` button can be skipped, so it looks like it’s working as intended. While not ideal, in my opinion muting ads is better than hearing them

**Comment by jt3dst** [comment]
Ok thank's

**Comment by cgriffith99** [comment]
> @cgriffith99 if it shows a device then it should be working. Do you mind sending logs of the container that show some device activity?

I'm wondering if that's the problem or not; I am not running in a container, I am running the bare python program on my PC.

**Comment by dmunozv04** [comment]
> I'm wondering if that's the problem or not; I am not running in a container, I am running the bare python program on my PC.
It should work fine in bare python too. Just make sure that the shell running iSponsorBlockTV stays open (`python main.py`should be running ). You can make a systemd service to do this, or run it on a screen. An automatic service installer would be a nice option for the future

**Comment by acgh213** [comment]
no issues for me, skipped a sponsored segment and connected right away. great work. 

android tv youtube app - all current as of this morning (10/14)
