### ISSUE TITLE
Seems to work fine on Roku

### ISSUE THREAD

**Issue by Scoth42** [dmunozv04/iSponsorBlockTV#68]
Saw that Roku was listed as untested, so tried this out with a couple of mine. Linked up fine with the codes and Just Works like magic. Completely fantastic.

**Comment by dmunozv04** [comment]
Thanks for testing it on Roku. Glad to hear it’s working great! Thanks. I’ll get the compatibility table updated

**Comment by Bleh55** [comment]
Not sure if it warrants a separate listing, but my TCL TV with built-in Roku is not working; works great on AppleTV.

**Comment by dmunozv04** [comment]
> Not sure if it warrants a separate listing, but my TCL TV with built-in Roku is not working; works great on AppleTV.

Do please open another issue if you wish to help investigate the cause there
