### ISSUE TITLE
"Could not load config file"

### ISSUE THREAD

**Issue by Darmach092** [dmunozv04/iSponsorBlockTV#69]
docker run --rm -it \
> -v /isponsorblocktv/app/data \
> --net=host \
> -e TERM=$TERM -e COLORTERM=$COLORTERM \
> ghcr.io/dmunozv04/isponsorblocktv \
> --setup

Running this on my raspberry pi through SSL (using root) keeps bringing me the error "Could not load config file"

**Comment by dmunozv04** [comment]
You seem to be missing a `:` on `-v /isponsorblocktv:/app/data`
Docker volumes need a source on the system and a destination on the container. 
Please let me know if this works.
This should be the full command:
```Shell
docker run --rm -it \
-v /isponsorblocktv:/app/data \
--net=host \
-e TERM=$TERM -e COLORTERM=$COLORTERM \
ghcr.io/dmunozv04/isponsorblocktv \
--setup
```

**Comment by Darmach092** [comment]
Note to self: don't do setups pre-morning coffee.
worked straight away thank you!

**Comment by dmunozv04** [comment]
Coffee definitely helps to catch mistakes, which we all have. Happy to know that it worked! You’re welcome
