### ISSUE TITLE
Prevents youtube Shorts from playing, tvOS

### ISSUE THREAD

**Issue by 24fpsDaVinci** [dmunozv04/iSponsorBlockTV#72]
apple tv 4k 2022
tvOS 17.1

an error message will show when trying to play youtube shorts:
"To watch this Short, your mobile device can't be connected to this tv"

**Comment by 24fpsDaVinci** [comment]
ah I missed it, thanks

**Comment by TheQuantumPhysicist** [comment]
Hi. I'm a new user, just discovered this great software very recently. Thank you for it.

I'm hitting this problem now. I like the fact that my TV doesn't have to be on the same network. Would using the API help fix this problem? Or is it over, either this or shorts?
