### ISSUE TITLE
Set up on LG TV works on YouTube but blocks all other streaming services

### ISSUE THREAD

**Issue by VMmatty** [dmunozv04/iSponsorBlockTV#73]
I've got this running as a container on an Ubuntu 20 VM and it works great for automatically skipping sponsored content in YouTube on my LG G3 TV.  I noticed after setting it up that I was then no longer able to stream any content from multiple streaming providers, including Netflix, Max, and Disney+.  I could bring up the UI and select something to stream but the result was the same on all of them - they tried to start streaming and eventually failed.  After I stopped the iSponsorBlockTV container I was immediately able to stream from these services.

The Docker container runs on an Ubuntu 20 VM running on ESXi (x86).  The device is an LG G3 OLED TV running the latest version of webOS.

I am not sure why this is interfering with other streaming services on the webOS TV but it clearly seems to be.  Any idea why this is happening?

**Comment by 24fpsDaVinci** [comment]
no issues here, i'm running webos latest version on the LG C1. Tested prime and appletv app. iSponsorblock paired with the internal youtube app and working correctly.

**Comment by dmunozv04** [comment]
That’s very weird. I’ll get the debug mode working soon and ping you when it’s ready so we can try to diagnose that weird issue. Just in case, could you try fully rebooting your TV @VMmatty  ?

**Comment by dmunozv04** [comment]
Thanks for the nice comment!
