### ISSUE TITLE
FYI - updated wiki installation instructions to enhance clarity

### ISSUE THREAD

**Issue by mgrimace** [dmunozv04/iSponsorBlockTV#80]
**Is your feature request related to a problem? Please describe.**
Within the Wiki, setting up the config.yml file uses a docker run command, hence it wasn't immediately clear that this is a separate step required before using docker compose (e.g., a two-step process).

**Describe the solution you'd like**
I updated the wiki docker install wording to attempt to make the installation steps clearer for new users, and those who may be unfamiliar with this process. 

**Describe alternatives you've considered**
Please feel free to edit further, or revert if you prefer the original. Please also review for any errors or innaccuracies. 

**Additional context**
Anecdotally tested new instructions with friends first.

**Comment by dmunozv04** [comment]
Thanks for making that change, I kinda forgot about the setup thing for `docker compose`! Wording is great, very easy to follow

**Comment by mgrimace** [comment]
> Thanks for making that change, I kinda forgot about the setup thing for `docker compose`! Wording is great, very easy to follow

Thanks! I didn’t want to make any changes without alerting you just in case, I appreciate your work on this!

**Comment by dmunozv04** [comment]
I appreciate the notice, and thanks!
