### ISSUE TITLE
Compatibility Feedback: Chromecast and Fire Stick Working as Expected

### ISSUE THREAD

**Issue by adripo** [dmunozv04/iSponsorBlockTV#87]
I've tested your project's compatibility with Chromecast and Fire Stick devices, and it works flawlessly in a local area network. This includes features like muting ads and automatic skip. Since your README states that Chromecast and Fire Stick are "not tested", I wanted to inform you about this successful test. Updating the README with this information could encourage more users with these devices to try out your project.

Thank you for your hard work on this project. It greatly enhances the YouTube TV experience!

**Comment by dmunozv04** [comment]
Thanks for the info and I’m happy to hear that it’s working great! I’ll get the readme table updated soon to reflect the compatibility of those devices.
