### ISSUE TITLE
Can't run the install script

### ISSUE THREAD

**Issue by Falenone** [dmunozv04/iSponsorBlockTV#93]
I was unable to set it up with docker using the documentation available so I did the git clone and tried that

instead of main.py --setup I had to do python main.py --setup

After that I get:

Traceback (most recent call last):
  File "/usr/home/iSponsorBlockTV/main.py", line 5, in <module>
    from . import api_helpers, ytlounge
ImportError: attempted relative import with no known parent package

**Comment by dmunozv04** [comment]
It seems like you're trying to run the `iSponsorBlockTV/main.py` file instead of the `main.py` file. Make sure you've cloned the whole repo.

**Comment by Falenone** [comment]
Yep that was my issue. Thank you
