### ISSUE TITLE
How do I verify I've done everything right?

### ISSUE THREAD

**Issue by Falenone** [dmunozv04/iSponsorBlockTV#94]
So after running the correct py script. I think I added the correct api key? I don't know, I got some api key from Google cloud and added that.
It didn't find my tv on the network for some reason so I added via the code, I saved it. Now what? Is it working, is it not? It isn't skipping any segments of known videos where it does skip them in my browser

**Comment by oxixes** [comment]
The API key is only required for the channels whitelist

**Comment by Falenone** [comment]
Running it on ubuntu server that sits on a tiny thin client that also runs my pihole. Opening youtube on my LG webos shows... the regular youtube, it plays videos like it always does. but it doesn't skip any sponsors

**Comment by oxixes** [comment]
I assume you're running main.py. iSponsorBlockTV should connect to the YouTube app (like a phone when you cast). Make sure you have configured it correctly. If nothing works, maybe @dmunozv04 has another suggestion.

**Comment by dmunozv04** [comment]
I just realized that the last commit broke getting segments. I'll push a new commit soon and that'll fix it. 
You'll have to do a `git pull` after that to see the changes.

**Comment by Falenone** [comment]
After running the main.py outside of the folder 

python main.py
Connected to device YouTube on TV
400, message='INVALID_REQUEST', url=URL('https://www.youtube.com/api/lounge/bc/bind?device=REMOTE_CONTROL&name=iSponsorBlockTV&app=youtube-desktop&loungeIdToken=AGdO5p_OsSZdI03QMB2A1AR8fZ2Fz6F1ycfi2ME6L089Ov22xTeg3tvk2q4fMjDl-Z2TNVuVegkk4RnvHp-b02kPsVrb5Rz39fDt-uH5q7UnSmCbUOzLCFc&VER=8&v=2&RID=18&SID=4C33F610E42A2EA5&AID=30&gsessionid=H5ZS2k21RkFUXgbfMhN1D_b2I3hJF65c')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyytlounge/wrapper.py", line 532, in _command
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='INVALID_REQUEST', url=URL('https://www.youtube.com/api/lounge/bc/bind?device=REMOTE_CONTROL&name=iSponsorBlockTV&app=youtube-desktop&loungeIdToken=blablatoken
401, message='RID_OUTSIDE_WINDOW', url=URL('https://www.youtube.com/api/lounge/bc/bind?device=REMOTE_CONTROL&name=iSponsorBlockTV&app=youtube-desktop&loungeIdToken=blabla token
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyytlounge/wrapper.py", line 532, in _command
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='RID_OUTSIDE_WINDOW', url=URL('https://www.youtube.com/api/lounge/bc/bind?device=REMOTE_CONTROL&name=iSponsorBlockTV&app=youtube-desktop&loungeIdToken=blabla token
Connected to device YouTube on TV

**Comment by dmunozv04** [comment]
Those sorts of errors seem to happen from time to time, so you can ignore them. If you now do a `git pull` and run the script again, segments should be detected and skipped

**Comment by Falenone** [comment]
Did git pull and now I don't get those errors anymore. It says playing *The video identifier or whatever* with 12 segments but nothing is skipped. on the tv it plays the entire video from start to finish

**Comment by shanmukhateja** [comment]
@Falenone I have the same problem. The videos aren't skipped on my Samsung TV (Tizen OS). I also see the "Playing xxxx with yy segments" text.

Just like yourself, I have added my TV via code (using CLI)

**Comment by shanmukhateja** [comment]
Update: It seems to be working however the skip feature won't work sometimes because segments were fetched a little late and video playback has moved the current time (of video) inside a "skip" section. 

**Related:** https://github.com/ajayyy/SponsorBlock/issues/124

I guess I can say it works as expected. 

Thanks devs for the amazing product!
